"""Generate description.md summarizing the built datasets.

Scans every built dataset under data/ (any dir with a data.yaml) and reports image
counts and per-class polygon counts per split — for each dataset and for the merged
one (broken down by source). Regenerate any time after building:

    uv run python -m oralskop.data.describe
"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

import yaml

from oralskop.data.verify import IMAGE_EXTS

AI_ROOT = Path(__file__).resolve().parents[2]


def _names(data_yaml: Path) -> dict[int, str]:
    n = yaml.safe_load(data_yaml.read_text()).get("names", {})
    return dict(enumerate(n)) if isinstance(n, list) else {int(k): v for k, v in n.items()}


def scan(ds_dir: Path) -> dict:
    """Per-split image counts + per-class polygon counts + per-source breakdown."""
    names = _names(ds_dir / "data.yaml")
    info = {"names": names, "images": {}, "polys": {}, "sources": Counter(),
            "source_polys": defaultdict(Counter)}
    for split in ("train", "val"):
        img_dir, lbl_dir = ds_dir / "images" / split, ds_dir / "labels" / split
        imgs = [p for p in img_dir.iterdir()
                if p.is_file() and p.suffix.lower() in IMAGE_EXTS] if img_dir.is_dir() else []
        info["images"][split] = len(imgs)
        hist: Counter = Counter()
        for p in imgs:
            src = p.stem.split("__")[0] if "__" in p.stem else ds_dir.name
            info["sources"][src] += 1
            lbl = lbl_dir / f"{p.stem}.txt"
            if lbl.exists():
                for line in lbl.read_text().splitlines():
                    if line.strip():
                        cid = int(line.split()[0])
                        hist[cid] += 1
                        info["source_polys"][src][cid] += 1
        info["polys"][split] = hist
    return info


def _class_table(info: dict) -> list[str]:
    names = info["names"]
    rows = ["| class | train polys | val polys |", "|---|--:|--:|"]
    present = sorted(set(info["polys"]["train"]) | set(info["polys"]["val"]))
    for cid in present:
        rows.append(f"| {cid} {names.get(cid, cid)} | "
                    f"{info['polys']['train'].get(cid, 0)} | {info['polys']['val'].get(cid, 0)} |")
    return rows


def render(datasets: dict[str, dict]) -> str:
    out = ["# OralSkop — Dataset Description", "",
           f"_Generated by `oralskop.data.describe` on {date.today().isoformat()} "
           f"from the built datasets under `data/`. Re-run to refresh._", ""]

    # Summary table
    out += ["## Summary", "",
            "| Dataset | Train imgs | Val imgs | Total | Classes with instances |",
            "|---|--:|--:|--:|---|"]
    for name, info in datasets.items():
        tr, va = info["images"].get("train", 0), info["images"].get("val", 0)
        present = sorted(set(info["polys"]["train"]) | set(info["polys"]["val"]))
        cls = ", ".join(info["names"].get(c, str(c)) for c in present)
        out.append(f"| {name} | {tr} | {va} | {tr + va} | {cls} |")
    out.append("")

    # Per-dataset detail
    for name, info in datasets.items():
        tr, va = info["images"].get("train", 0), info["images"].get("val", 0)
        out += [f"## {name}", "",
                f"- **Images:** {tr} train + {va} val = **{tr + va}**", ""]
        out += _class_table(info) + [""]
        if len(info["sources"]) > 1:  # merged: show per-source breakdown
            out += ["**By source dataset:**", "",
                    "| source | images | polygons |", "|---|--:|--:|"]
            for src, n in sorted(info["sources"].items()):
                out.append(f"| {src} | {n} | {sum(info['source_polys'][src].values())} |")
            out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser(description="Generate description.md for built datasets.")
    p.add_argument("--data-root", default=str(AI_ROOT / "data"))
    p.add_argument("--out", default=str(AI_ROOT / "description.md"))
    args = p.parse_args(argv)

    data_root = Path(args.data_root)
    found = {d.name: scan(d) for d in sorted(data_root.iterdir())
             if d.is_dir() and (d / "data.yaml").exists()}
    if not found:
        raise SystemExit(f"No built datasets under {data_root}. Run prepare first.")
    # Put merged/multi-source datasets last.
    ordered = dict(sorted(found.items(), key=lambda kv: (len(kv[1]["sources"]) > 1, kv[0])))

    Path(args.out).write_text(render(ordered))
    print(f"Wrote {args.out} ({len(ordered)} datasets: {', '.join(ordered)})")


if __name__ == "__main__":
    main()
